[versions]
agp = "8.11.2"
hiltCompilerVersion = "1.3.0"
hiltNavigationCompose = "1.3.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"

#Hilt
hiltAndroid = "2.56.2"
hiltCompiler = "1.2.0"

#JSON
kotlinxSerializationJson = "1.7.3"
kotlinxDatetime = "0.6.2"

#Retrofit
materialVersion = "1.10.1"
moshiKotlin = "1.15.2"
retrofit = "2.9.0"
loggingInterceptor = "4.3.1"
retrofit2KotlinxSerializationConverter = "0.8.0"


#???
navigationFragmentKtx = "2.9.0"
navigationUiKtx = "2.9.0"
ui = "1.10.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

#Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }

#androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref ="appcompat" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

#Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }

#androidx-hilt-compiler-v130 = { module = "androidx.hilt:hilt-compiler", version.ref ="hiltCompilerVersion" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }


androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

#JSON
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name="kotlinx-datetime", version.ref ="kotlinxDatetime" }

#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

#Hilt
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }

#Kotlin Serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

#compose
# similar a kotlin-android org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android",version.ref = "kotlin"}
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}