[versions]
#agp = "8.11.2"
agp = "8.7.3"
hiltNavigationCompose = "1.2.0"
kotlin = "2.1.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"

espressoCore = "3.6.1"
activity = "1.9.3"

#Hilt
hiltAndroid = "2.52"
hiltCompiler = "1.2.0"

#JSON
kotlinxSerializationJson = "1.10.0"
kotlinxDatetime = "0.6.1"

#Retrofit
retrofit = "2.11.0"
moshiKotlin = "1.15.2"
loggingInterceptor = "4.12.0"
retrofit2KotlinxSerializationConverter = "1.0.0"



#Room estable
#roomRuntime = "2.6.1"
roomRuntime = "2.7.0-alpha11"
runtimeLivedata = "1.7.5"
ui = "1.7.5"
materialVersion = "1.7.5"

material3 = "1.3.1"
gMaterial = "1.12.0"
ksp = "2.1.0-1.0.29"

#Charts
#Vico
vico = "3.0.0-beta.3"

#Charty
charty = "3.0.0-rc01"


[libraries]

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

#Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }

#Serialization
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }


junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

#Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
#androidx-material = { module = "androidx.compose.material:material", version.ref ="materialVersion" }

androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-material3-icons = { group = "androidx.compose.material3", name ="material3-icons-extended", version.ref = "material3" }
google-material = { group = "com.google.android.material", name = "material", version.ref="gMaterial" }

#androidx-material-icons = { group = "androidx.compose.material", name ="material-icons-core",version.ref = "material" }
#androidx-material-icons-extended = { group = "androidx.compose.material",name="material-icons-extended", version.ref = "material" }

androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

#Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }


#JSON
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name="kotlinx-datetime", version.ref ="kotlinxDatetime" }

#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }

#Charts
#Vico
# Compose Multiplatform
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
# Material 2 theming in Compose Multiplatform
vico-compose-m2 = { group = "com.patrykandpatrick.vico", name = "compose-m2", version.ref = "vico" }
# Material 3 theming in Compose Multiplatform
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
# Android view system
vico-views = { group = "com.patrykandpatrick.vico", name = "views", version.ref = "vico" }

#Charty
charty = { module = "com.himanshoe:charty", version.ref = "charty" }

[plugins]

devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" } # Versi√≥n para Kotlin 2.1.0


android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

#Hilt
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }

#Kotlin Serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

#compose
# similar a kotlin-android org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android",version.ref = "kotlin"}
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}